[package]
name = "stackforge-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Core networking logic for Stackforge."

[dependencies]
thiserror.workspace = true
bytes.workspace = true
smallvec.workspace = true
pnet_datalink = "0.35.0"
default-net = "0.22.0"
rand = { version = "0.9.2", optional = true }
pcap-file = "2"

[features]
default = ["rand"]

[lints]
workspace = true
