__version__ = "0.2.0"

# Re-export all public classes from the Rust extension
from stackforge.stackforge import (
    ARP,
    COTP,
    DNP3,
    FTP,
    HTTP,
    HTTP2,
    ICMP,
    IEC104,
    IMAP,
    IP,
    L2TP,
    MQTT,
    MQTTSN,
    POP3,
    QUIC,
    SMTP,
    SSH,
    TCP,
    TFTP,
    TLS,
    TPKT,
    UDP,
    # Anonymization
    AnonymizationPolicy,
    # Automata (AnsweringMachine framework)
    AnsweringMachine,
    AutomatonConfig,
    # ICS/IoT protocols
    CoAP,
    # Flow extraction
    Conversation,
    DhcpPoolConfig,
    DhcpServerAM,
    Ether,
    FlowConfig,
    HTTPResponse,
    ICMPv6,
    # New protocol builders
    IPv6,
    LayerIndex,
    LayerKind,
    LayerStack,
    Modbus,
    Packet,
    PcapPacket,
    PcapReader,
    Raw,
    S7Comm,
    Sniffer,
    WorkerPool,
    ZWave,
    extract_flows,
    extract_flows_from_packets,
    list_interfaces,
    parse_batch,
    rdpcap,
    sniff,
    validate_filter,
    wrpcap,
    wrpcapng,
)

from .custom import (
    ByteField,
    CustomLayer,
    IntField,
    LongField,
    ShortField,
    StrLenField,
    get_protocol,
    list_protocols,
)

__all__ = [
    "Packet",
    "LayerKind",
    "LayerIndex",
    # Layer builders
    "Ether",
    "IP",
    "TCP",
    "UDP",
    "ARP",
    "ICMP",
    "SSH",
    "TLS",
    "Raw",
    "LayerStack",
    # New protocol builders
    "IPv6",
    "ICMPv6",
    "HTTP",
    "HTTPResponse",
    "QUIC",
    "HTTP2",
    "L2TP",
    "MQTT",
    "MQTTSN",
    "Modbus",
    "ZWave",
    "FTP",
    "TFTP",
    "SMTP",
    "POP3",
    "IMAP",
    # ICS/IoT protocols
    "CoAP",
    "TPKT",
    "COTP",
    "S7Comm",
    "IEC104",
    "DNP3",
    # PCAP I/O
    "rdpcap",
    "wrpcap",
    "wrpcapng",
    "PcapPacket",
    "PcapReader",
    # Anonymization
    "AnonymizationPolicy",
    # Flow extraction
    "Conversation",
    "FlowConfig",
    "extract_flows",
    "extract_flows_from_packets",
    # Sniffer & Performance
    "Sniffer",
    "WorkerPool",
    "sniff",
    "parse_batch",
    "list_interfaces",
    "validate_filter",
    # Automata (AnsweringMachine framework)
    "AnsweringMachine",
    "AutomatonConfig",
    "DhcpPoolConfig",
    "DhcpServerAM",
    # Custom protocol API
    "CustomLayer",
    "ByteField",
    "ShortField",
    "IntField",
    "LongField",
    "StrLenField",
    "get_protocol",
    "list_protocols",
    "__version__",
]
