"""Type stubs for the stackforge package."""

from typing import Any, Callable, Optional, Union

from stackforge.stackforge import (
    ARP as ARP,
    FTP as FTP,
    HTTP as HTTP,
    HTTP2 as HTTP2,
    ICMP as ICMP,
    IMAP as IMAP,
    IP as IP,
    L2TP as L2TP,
    MQTT as MQTT,
    MQTTSN as MQTTSN,
    POP3 as POP3,
    QUIC as QUIC,
    SMTP as SMTP,
    SSH as SSH,
    TCP as TCP,
    TFTP as TFTP,
    TLS as TLS,
    UDP as UDP,
    AnsweringMachine as AnsweringMachine,
    AutomatonConfig as AutomatonConfig,
    Conversation as Conversation,
    DhcpPoolConfig as DhcpPoolConfig,
    DhcpServerAM as DhcpServerAM,
    Ether as Ether,
    FlowConfig as FlowConfig,
    HTTPResponse as HTTPResponse,
    ICMPv6 as ICMPv6,
    IPv6 as IPv6,
    LayerIndex as LayerIndex,
    LayerKind as LayerKind,
    LayerStack as LayerStack,
    Modbus as Modbus,
    Packet as Packet,
    PcapPacket as PcapPacket,
    PcapReader as PcapReader,
    Raw as Raw,
    Sniffer as Sniffer,
    ZWave as ZWave,
    extract_flows as extract_flows,
    extract_flows_from_packets as extract_flows_from_packets,
    list_interfaces as list_interfaces,
    rdpcap as rdpcap,
    sniff as sniff,
    validate_filter as validate_filter,
    wrpcap as wrpcap,
    wrpcapng as wrpcapng,
)
from stackforge.custom import (
    ByteField as ByteField,
    CustomLayer as CustomLayer,
    IntField as IntField,
    LongField as LongField,
    ShortField as ShortField,
    StrLenField as StrLenField,
    get_protocol as get_protocol,
    list_protocols as list_protocols,
)

__version__: str
__all__: list[str]
